#!/usr/bin/perl

#Open a file, find a string and replace it
#First arg: What to look for (include escape chars)
#Second arg: What to replace the match with (don't include escape chars)
#Third arg; What file to use
#All args in single quotes
#Author: Avix

use strict;
use warnings;

my $find =  $ARGV[0];
my $replace = $ARGV[1];
my $filename = $ARGV[2];
print "Finding... $find\n";
print "Replacing with... $replace\n";
print "In File... $filename\n";
     
my $data = read_file($filename);
$data =~ s/$find/$replace/g;
write_file($filename, $data);
print "File Overwrite Complete!\n";
exit;
     
sub read_file {
    my ($filename) = @_;
     
    open my $in, '<:encoding(UTF-8)', $filename or die "Could not open '$filename' for reading $!";
    local $/ = undef;
    my $all = <$in>;
    close $in;
     
    return $all;
}
     
sub write_file {
    my ($filename, $content) = @_;
     
    open my $out, '>:encoding(UTF-8)', $filename or die "Could not open '$filename' for writing $!";;
    print $out $content;
    close $out;
     
    return;
}
